### ISSUE TITLE
select 박스에서 value 값이 없는 부분 선택 시 문제점

### ISSUE THREAD

**Issue by suromind** [ax5ui/ax5ui-select#1]
안녕하십니까`

ax5ui-select 를 사용중에 문의점이 있어서 질문 올립니다.
javascript에서 생성하고 나면

![image](https://cloud.githubusercontent.com/assets/6029186/22007825/1a250560-dcb9-11e6-86cf-009a806baa37.png)

이런형태로 코드가 나온상태에서
경영기획팀을 선택했다가 다시 -- 전체 -- 를 선택하면 전체가 선택되지 않고
그대로 경영기획팀이 계속 선택되어진 상태입니다.

아무래도 value값이 없는경우에는 선택이 안되는 것 같네요

다른문제가 있는 싶어서 최신버전으로 해도 같은 현상이네요
파이어폭스 및 크롬에서 테스트해 보았습니다.

axisj에서는 괜찮았는데요..ㅜ
확인 부탁드립니다.

**Comment by thomasJang** [comment]
네 확인하겠습니다

**Comment by thomasJang** [comment]
패치 하였습니다. 
ax5select를 새 버전으로 교체 하고 확인해주세요.

**Comment by suromind** [comment]
감사합니다. 확인해보니 잘됩니다^^
