### ISSUE TITLE
jQuery 1.9 버전 지원 문의

### ISSUE THREAD

**Issue by TaeSeong** [ax5ui/ax5ui-select#2]
안녕하세요. 이전 AXJUI를 사용하다 이번에 AX5UI를 적용하려고 보고있는데

샘플 예제처럼 jQuery 1.12.4를 사용하면 예제가 실행되는데

jQuery 1.9 버전에서는 

`Uncaught Error: Syntax error, unrecognized expression: <a href="#ax5select-ax5select-3" class="form-control  ax5select-display default" 
data-ax5select-display="ax5select-3" data-ax5select-instance="2">
    <div class="ax5select-display-table" data-els="display-table">
        <div data-ax5select-display="label">optionText0</div>
        <div data-ax5select-display="addon"> 
            <span class="addon-icon-closed"><span class="addon-icon-arrow"></span></span>
            <span class="addon-icon-opened"><span class="addon-icon-arrow"></span></span>
        </div>
    </div>
    <input type="text" tabindex="-1" data-ax5select-display="input" 
    style="position:absolute;z-index:0;left:0px;top:0px;font-size:1px;opacity: 0;width:1px;border: 0px none;color : transparent;text-indent: -9999em;" />
</a>
    at Function.st.error (jquery-1.9.1.min.js:3)
    at ft (jquery-1.9.1.min.js:3)
    at wt (jquery-1.9.1.min.js:3)
    at Function.st [as find] (jquery-1.9.1.min.js:3)
    at init.find (jquery-1.9.1.min.js:3)
    at init (jquery-1.9.1.min.js:2)
    at b (jquery-1.9.1.min.js:2)
    at e.get (ax5select-tmpl.js:115)
    at e.<anonymous> (ax5select.js:457)
    at e.bind (ax5select.js:745)
st.error @ jquery-1.9.1.min.js:3
ft @ jquery-1.9.1.min.js:3
wt @ jquery-1.9.1.min.js:3
st @ jquery-1.9.1.min.js:3
find @ jquery-1.9.1.min.js:3
init @ jquery-1.9.1.min.js:2
b @ jquery-1.9.1.min.js:2
get @ ax5select-tmpl.js:115
(anonymous) @ ax5select.js:457
bind @ ax5select.js:745
(anonymous) @ ax5select.js:1240
each @ jquery-1.9.1.min.js:2
(anonymous) @ ax5select.js:1235
(anonymous) @ write.do?mId=0102030000:931
c @ jquery-1.9.1.min.js:2
fireWith @ jquery-1.9.1.min.js:2
ready @ jquery-1.9.1.min.js:2
H @ jquery-1.9.1.min.js:2`

위와 같은 에러가 발생하는데 1.9는 지원하지 않는 버전인가요??

**Comment by thomasJang** [comment]
지원은 모르겠구요. 테스트 해본적이 없습니다.
그리고 지원할 계획이 없습니다. 1.10 이상을 권장합니다.

**Comment by thomasJang** [comment]
https://blog.jquery.com/2013/05/24/jquery-1-10-0-and-2-0-1-released/ 여기 문서 한번봐주세요.

**Comment by TaeSeong** [comment]
답변해주셔서 감사합니다.
레거시라서 1.9로 되어있는 프로젝트의 jQuery 버전을 올리기로 하였습니다.
감사합니다. :+1:
